services:
  hikvision-camera-bot:
    container_name: "hikvision_camera_bot"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # The first path is a real local storage path e.g., "D:\Videos" in Windows. Change to your preferred one.
      - "/data/dvr:/data/dvr"
      - "/data/timelapses:/data/timelapses"
      - "./configs:/app/configs"
    restart: unless-stopped
    depends_on:
      - hikvision-srs-server
    command: >
      bash -c "python ./bot.py"

  hikvision-srs-server:
    container_name: "hikvision_srs_server"
    env_file:
      - .env
    build:
      context: .
      dockerfile: srs_prod/Dockerfile
    tmpfs:
      # Store HLS .ts files in RAM. Depending on 'hls_fragment' and 'hls_window' default size '128M' might be increased.
      # Check usage inside the container with 'df -h'.
      - /srs/trunk/objs/nginx/html/hls:mode=770,size=128M
    volumes:
      - "./srs_prod:/usr/local/srs/user_conf"
    command: >
      bash -c "./objs/srs -c user_conf/hik-docker.conf"
    ports:
      # SRS RTMP port. If you comment this out, you won't be able to connect with video player like VLC.
      - "1935:1935"
      # SRS WebUI port. Also serves HLS stream; same warning as for previous port mapping.
      - "8080:8080"
